### ISSUE TITLE
Meson failed to configure

### ISSUE THREAD

**Issue by cjfloss** [Df458/Singularity#38]
> Project name: singularity
> Native C compiler: cc (gcc 5.4.0)
> Native Vala compiler: valac (valac 0.36.8)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.29.1)
> Native dependency glib-2.0 found: YES 2.48.2
> Native dependency gobject-2.0 found: YES 2.48.2
> 
> Meson encountered an error in file meson.build, line 11, column 0:
> Vala library 'gcrypt' not found

**Comment by cjfloss** [comment]
I have libgcrypt20-dev and libgcrypt11-dev installed

**Comment by Df458** [comment]
Can you try the latest commit? I've added the vapi to the repo, so it should be able to find the configure now.

**Comment by cjfloss** [comment]
Meson configures fine, but building with ninja return this error

> 
> FAILED: src/lib/singularity@sta/meson-generated_AtomItemDataSource.c.o 
> cc  -Isrc/lib/singularity@sta -Isrc/lib -I../src/lib -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gee-0.8 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/webkitgtk-4.0 -I/usr/local/include/gxml-0.14 -I/usr/include/sqlheavy/sqlheavy-0.1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w -O0 -g -fPIC -pthread -MMD -MQ 'src/lib/singularity@sta/meson-generated_AtomItemDataSource.c.o' -MF 'src/lib/singularity@sta/meson-generated_AtomItemDataSource.c.o.d' -o 'src/lib/singularity@sta/meson-generated_AtomItemDataSource.c.o' -c 'src/lib/singularity@sta/AtomItemDataSource.c'
> src/lib/singularity@sta/AtomItemDataSource.c:25:19: fatal error: dflib.h: No such file or directory
> compilation terminated.
> [16/70] Compiling C object 'src/lib/singularity@sta/meson-generated_Attachment.c.o'.
> FAILED: src/lib/singularity@sta/meson-generated_Attachment.c.o 
> cc  -Isrc/lib/singularity@sta -Isrc/lib -I../src/lib -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gee-0.8 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/webkitgtk-4.0 -I/usr/local/include/gxml-0.14 -I/usr/include/sqlheavy/sqlheavy-0.1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w -O0 -g -fPIC -pthread -MMD -MQ 'src/lib/singularity@sta/meson-generated_Attachment.c.o' -MF 'src/lib/singularity@sta/meson-generated_Attachment.c.o.d' -o 'src/lib/singularity@sta/meson-generated_Attachment.c.o' -c 'src/lib/singularity@sta/Attachment.c'
> src/lib/singularity@sta/Attachment.c:24:19: fatal error: dflib.h: No such file or directory
> compilation terminated.
> [17/70] Compiling C object 'src/lib/singularity@sta/meson-generated_CollectionNode.c.o'.
> FAILED: src/lib/singularity@sta/meson-generated_CollectionNode.c.o 
> cc  -Isrc/lib/singularity@sta -Isrc/lib -I../src/lib -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gee-0.8 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/webkitgtk-4.0 -I/usr/local/include/gxml-0.14 -I/usr/include/sqlheavy/sqlheavy-0.1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w -O0 -g -fPIC -pthread -MMD -MQ 'src/lib/singularity@sta/meson-generated_CollectionNode.c.o' -MF 'src/lib/singularity@sta/meson-generated_CollectionNode.c.o.d' -o 'src/lib/singularity@sta/meson-generated_CollectionNode.c.o' -c 'src/lib/singularity@sta/CollectionNode.c'
> src/lib/singularity@sta/CollectionNode.c:24:19: fatal error: dflib.h: No such file or directory
> compilation terminated.
> [18/70] Compiling C object 'src/lib/singularity@sta/meson-generated_CollectionRequest.c.o'.
> FAILED: src/lib/singularity@sta/meson-generated_CollectionRequest.c.o 
> cc  -Isrc/lib/singularity@sta -Isrc/lib -I../src/lib -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gee-0.8 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/webkitgtk-4.0 -I/usr/local/include/gxml-0.14 -I/usr/include/sqlheavy/sqlheavy-0.1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w -O0 -g -fPIC -pthread -MMD -MQ 'src/lib/singularity@sta/meson-generated_CollectionRequest.c.o' -MF 'src/lib/singularity@sta/meson-generated_CollectionRequest.c.o.d' -o 'src/lib/singularity@sta/meson-generated_CollectionRequest.c.o' -c 'src/lib/singularity@sta/CollectionRequest.c'
> src/lib/singularity@sta/CollectionRequest.c:25:19: fatal error: dflib.h: No such file or directory
> compilation terminated.
> [20/70] Compiling C object 'src/lib/singularity@sta/meson-generated_CollectionTreeStore.c.o'.
> FAILED: src/lib/singularity@sta/meson-generated_CollectionTreeStore.c.o 
> cc  -Isrc/lib/singularity@sta -Isrc/lib -I../src/lib -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gee-0.8 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/webkitgtk-4.0 -I/usr/local/include/gxml-0.14 -I/usr/include/sqlheavy/sqlheavy-0.1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w -O0 -g -fPIC -pthread -MMD -MQ 'src/lib/singularity@sta/meson-generated_CollectionTreeStore.c.o' -MF 'src/lib/singularity@sta/meson-generated_CollectionTreeStore.c.o.d' -o 'src/lib/singularity@sta/meson-generated_CollectionTreeStore.c.o' -c 'src/lib/singularity@sta/CollectionTreeStore.c'
> src/lib/singularity@sta/CollectionTreeStore.c:26:19: fatal error: dflib.h: No such file or directory
> compilation terminated.
> ninja: build stopped: subcommand failed.

**Comment by cjfloss** [comment]
I tried building manually and installing dflib

> [0/1] Installing files.
> Installing src/libdflib.so to /usr/local/lib/x86_64-linux-gnu/libdflib.so
> Installing /home/cleiton/Projects/Singularity/subprojects/dflib/build/meson-private/dflib.pc to /usr/local/lib/x86_64-linux-gnu/pkgconfig

but it does not solve the problem

**Comment by Df458** [comment]
Sorry about that! I forgot to clear headers when testing the configuration changes. I've already committed the fix to dflib, so this should compile properly if you delete the `subprojects/dflib` folder.

**Comment by cjfloss** [comment]
Now it's compiling but when I try to execute I get this error

> (singularity:4124): Gtk-CRITICAL **: Error building template class 'MainWindow' for an instance of type 'MainWindow': .:3:50 Required gtk+ version 3.20, current version is 3.18

**Comment by Df458** [comment]
Sounds like you have an old version of gtk installed. What distro are you running at the moment?

**Comment by cjfloss** [comment]
elementaryOS Loki

**Comment by Df458** [comment]
Looks like the distro is still on 3.18. Anyway, I've updated the UI templates to accept GTK+ version 3.18, can't test on my end but I don't think I'm currently using any 3.20+ features right now. Let me know if that helps at all!

**Comment by cjfloss** [comment]
It is working but the window don't have buttons(close,maximize)

![singularity](https://user-images.githubusercontent.com/5838486/35022794-9380ef74-fb16-11e7-8d3f-401e4110f12b.png)

**Comment by Df458** [comment]
Ah, that might be my fault, I have those buttons disabled in my GTK config so I never noticed them missing. One sec, I'll put them in.

**Comment by Df458** [comment]
Ok, should be fixed now. I'm closing the issue since the app clearly builds now. If you have any other problems, feel free to open a new issue about them.
